### ISSUE TITLE
How to add new row into datatable

### ISSUE THREAD

**Issue by atomsbaza** [datasweet/datatable#18]
For example

> dataTableExamForAdd := datatable.New("ExamForAdd")
> dataTableExamForAdd.AddColumn("ContactId", datatable.String)
> dataTableExamForAdd.AddColumn("CourseId", datatable.String)
> dataTableExamForAdd.AddColumn("ClassId", datatable.String)
> dataTableExamForAdd.AddColumn("ContentId", datatable.String)
> dataTableExamForAdd.AddColumn("ExamId", datatable.String)

> for i := 0; i < len(Data); i++ {
> 		dataRow := dataTableExamForAdd.NewRow()
> 		dataRow.Set("ContactId", ExamData[i].ContactId)
> 		dataRow.Set("CourseId", ExamData[i].CourseId)
> 		dataRow.Set("ClassId", ExamData[i].ClassId)
> 		dataRow.Set("ContentId", ExamData[i].ContentId)
> 		dataRow.Set("ExamId", ExamData[i].ExamId)
> }

**Comment by charlotth** [comment]
Hello @atomsbaza 
Check this example https://github.com/datasweet/datatable/blob/master/table_test.go#L41 and https://github.com/datasweet/datatable/blob/master/table_test.go#L157
And sorry for the delay

**Comment by atomsbaza** [comment]
> Hello @atomsbaza Check this example https://github.com/datasweet/datatable/blob/master/table_test.go#L41 and https://github.com/datasweet/datatable/blob/master/table_test.go#L157 And sorry for the delay

Thank you for the replay but I already solve this problem
